CREATE TABLE users (
    id BIGINT PRIMARY KEY,
	fullname VARCHAR NOT NULL,
	contact VARCHAR NOT NULL,
	role VARCHAR NOT NULL,
	email VARCHAR NOT NULL,
	password VARCHAR NOT NULL,
	firebase_token VARCHAR,
	is_expired BOOLEAN NOT NULL DEFAULT FALSE,
	is_credentials_none_expired BOOLEAN NOT NULL DEFAULT FALSE,
	is_locked BOOLEAN NOT NULL DEFAULT FALSE,
	is_enabled BOOLEAN NOT NULL DEFAULT FALSE,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE jobs (
    id BIGINT PRIMARY KEY,
	user_id INTEGER NOT NULL,
	job_category_id_fk INTEGER NOT NULL,
	title VARCHAR NOT NULL,
	description VARCHAR NOT NULL,
    salary DECIMAL NOT NULL,
    longitude DECIMAL NOT NULL,
    latitude DECIMAL NOT NULL,
    job_start_time VARCHAR,
    job_end_time VARCHAR,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE settings (
    id BIGINT PRIMARY KEY,
    user_id INTEGER NOT NULL,
	username VARCHAR UNIQUE NOT NULL,
	password VARCHAR NOT NULL,
	is_biometric BOOLEAN NOT NULL DEFAULT FALSE,
	member_role VARCHAR NOT NULL,
	currency VARCHAR,
	radius INTEGER,
	member_start_time DATE,
	email VARCHAR UNIQUE NOT NULL,
	ask_permissions_before_deleting_a_job BOOLEAN DEFAULT FALSE,
	show_information_on_startup BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE,
	last_login TIMESTAMP WITH TIME ZONE
);

CREATE TABLE job_applications (
    id BIGINT PRIMARY KEY,
	username VARCHAR UNIQUE NOT NULL,
	password VARCHAR NOT NULL,
	email VARCHAR UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE,
	last_login TIMESTAMP WITH TIME ZONE
);

CREATE TABLE job_categories (
    id BIGINT PRIMARY KEY,
	username VARCHAR UNIQUE NOT NULL,
	password VARCHAR NOT NULL,
	email VARCHAR UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE,
	last_login TIMESTAMP WITH TIME ZONE
);

CREATE SEQUENCE hibernate_sequence START 1;