ALTER TABLE users
ALTER COLUMN id UUID GENERATED ALWAYS AS IDENTITY;

ALTER TABLE jobs
ALTER COLUMN id UUID GENERATED ALWAYS AS IDENTITY;

ALTER TABLE settings
ALTER COLUMN id UUID GENERATED ALWAYS AS IDENTITY;

ALTER TABLE job_applications
ALTER COLUMN id UUID GENERATED ALWAYS AS IDENTITY;

ALTER TABLE job_categories
ALTER COLUMN id UUID GENERATED ALWAYS AS IDENTITY;