ALTER TABLE users
ALTER COLUMN id INTEGER PRIMARY KEY;

ALTER TABLE jobs
ALTER COLUMN id INTEGER PRIMARY KEY;

ALTER TABLE settings
ALTER COLUMN id INTEGER PRIMARY KEY;

ALTER TABLE job_applications
ALTER COLUMN id INTEGER PRIMARY KEY;

ALTER TABLE job_categories
ALTER COLUMN id INTEGER PRIMARY KEY;