CREATE TABLE comments (
	id serial PRIMARY KEY,
	job_id INTEGER,
	user_id INTEGER,
	comment VARCHAR ( 255 ),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE,
    deleted_at TIMESTAMP WITH TIME ZONE,
);